### ISSUE TITLE
cannot initialize the project

### ISSUE THREAD

**Issue by netchampfaris** [tmaximini/generator-ionic-gulp#25]
when i run `yo ionic-gulp` i get the following error message:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 AssertionError: Trying to copy from a source that does not exist: C:\Users\netch\AppData\Roaming\npm\node_modules\generator-ionic-gulp\app\templates\_vendor.json
    at EditionInterface.exports._copySingle (C:\Users\netch\AppData\Roaming\npm\node_modules\generator-ionic-gulp\node_modules\mem-fs-editor\actions\copy.js:44:3)
    at EditionInterface.exports.copy (C:\Users\netch\AppData\Roaming\npm\node_modules\generator-ionic-gulp\node_modules\mem-fs-editor\actions\copy.js:22:17)
    at module.exports.yeoman.generators.Base.extend.writing.projectfiles (C:\Users\netch\AppData\Roaming\npm\node_modules\generator-ionic-gulp\app\index.js:263:15)
    at C:\Users\netch\AppData\Roaming\npm\node_modules\generator-ionic-gulp\node_modules\yeoman-generator\lib\base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by tmaximini** [comment]
thx, it seems I forgot to remove a copy statement for a deleted file. Should be fixed with https://github.com/tmaximini/generator-ionic-gulp/commit/871eda5a393cf0a5452487ba8af4ae8646f0941a 

Please update the generator to the latest version `1.4.1` and try again, thanks.

**Comment by netchampfaris** [comment]
it worked, thanks
