### ISSUE TITLE
Possible Missing Package?

### ISSUE THREAD

**Issue by keithbarrow** [tmaximini/generator-ionic-gulp#26]
`jshint` doesn't seem to be installed with the other packages. I followed the ReadMe instructions on a relatively vanilla machine, and got the following error:

```
[16:50:55] Starting 'jsHint'...
[16:50:55] 'jsHint' errored after 30 ms
[16:50:55] Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/keith.barrow/Documents/ionic/doric/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/keith.barrow/Documents/ionic/doric/node_modules/gulp-jshint/src/index.js:2:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
[16:50:55] 'default' errored after 1.71 s
[16:50:55] Error in plugin 'run-sequence'
```

`npm install jshint` fixed the problem - `jshint-stylish` is included in `package.json`
OSX Yosemite, Node v4.2.4, NPM 3.5.3 for what it is worth.

Thanks!

**Comment by tmdevde** [comment]
ran into the same error today. thanks for the tip!
