### ISSUE TITLE
New project required installed gulp-iconfont to be installed...

### ISSUE THREAD

**Issue by rinav** [tmaximini/generator-ionic-gulp#5]
I created new project and after running gulp it throws following error

```
[18:58:13] Using gulpfile ~/mnt/workspace/ionicApps/myApp-gulp/gulpfile.js
[18:58:13] Starting 'default'...
[18:58:13] Starting 'clean'...
[18:58:13] Finished 'clean' after 4.8 ms
[18:58:13] Starting 'iconfont'...
[18:58:14] 'iconfont' errored after 95 ms
[18:58:14] AssertionError: missing path
at Module.require (module.js:363:3)
at require (module.js:384:17)
at requireFn (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp-load-plugins/index.js:37:14)
at Object.defineProperty.get (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp-load-plugins/index.js:68:18)
at Gulp.<anonymous> (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/gulpfile.js:168:18)
at module.exports (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
at Gulp.Orchestrator._runTask (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
at Gulp.Orchestrator._runStep (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
at Gulp.Orchestrator.start (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
at runNextSet (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/run-sequence/index.js:79:16)


[18:58:14] 'default' errored after 104 ms
[18:58:14] Error: [object Object]
at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
at Gulp.emit (events.js:129:20)
at Gulp.Orchestrator._emitTaskDone (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
at /home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/index.js:275:23
at finish (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
at cb (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
at finish (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/run-sequence/index.js:53:5)
at Gulp.onError (/home/rinav/mnt/workspace/ionicApps/myApp-gulp/node_modules/run-sequence/index.js:60:4)
at Gulp.emit (events.js:129:20)
```

I then went and globally **installed gulp-iconfont** (just trying if that's what the error is)
and also locally installed it locally inside the project using npm

**and it did the trick...**

maybe you need to look into the stackstrace

**Comment by tmaximini** [comment]
Hi, thanks for reporting this. `gulp-iconfont` is listed as a dependency in the generated `package.json`, see https://github.com/tmaximini/generator-ionic-gulp/blob/master/app/templates/_package.json#L19.
Maybe your initial npm install did not go through correctly and that caused the error.

**Comment by rinav** [comment]
yeah I too think that might be the issue...
anyways, thanks for the great generator project :)
